<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="MAIN" Id="{1545be35-79c0-49e0-9439-af023340e6dc}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	StringBuilderExample : CStringBuilderExample;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[StringBuilderExample.RunExample();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="25" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>